@startuml activity-diagram create user
|Administrator|
start
:Submit create user form;

|Backend|
if (Form valid?) then (yes)
    :Check user creation limits;

    if (Can create more users?) then (yes)
        :Retrieve base entry;
        :Construct user attributes;
        :Add user to LDAP;

        if (User added successfully?) then (yes)
            if (Base is group?) then (yes)
                :Add user to group;
            endif
            :Return Success;
        else (no)
            :Handle errors;
            :Return Error (e.g., Already exists error, Insufficient access error);
        endif
    else (no)
        :Handle user creation limits error;
        :Return Error (e.g., Reached user limit);
    endif
else (no)
    :Handle form validation error;
    :Return error (e.g., Invalid form data);
endif

|Administrator|
:See the result;

stop
@enduml
